name: For each PR
on:
  pull_request:
    paths-ignore:
    - kernel/**
jobs:
  validation:
    runs-on: ubuntu-20.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.1.0

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build and push bootkit
      uses: docker/build-push-action@v2
      with:
        context: ./bootkit/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: localhost:5000/tinkerbell/hook-bootkit:0.0

    - name: Build and push tink-docker
      uses: docker/build-push-action@v2
      with:
        context: ./tink-docker/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: localhost:5000/tinkerbell/hook-docker:0.0

    - run: sed -e 's/quay.io/localhost:5000/g' hook.yaml > hook-ci.yaml

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: ./hack/ci-build.sh
      env:
        LINUXKIT_CONFIG: hook-ci.yaml
        GIT_VERSION: ${{ github.sha }}

    # TODO: add artifacts for the built images
    - uses: actions/upload-artifact@v2
      with:
        name: hook-${{ github.sha }}.tar.gz
        path: hook-${{ github.sha }}.tar.gz
