name: For each Kernel PR
on:
  pull_request:
    paths:
    - kernel/**
    - "!kernel/README.md"
jobs:
  kernel-validation:
    runs-on: self-hosted
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4

    - run: echo "REGISTRY=$(ip addr show dev bond0 | awk '$1 == "inet" { sub("/.*", "", $2); print $2 }' | head -n 1)" >> $GITHUB_ENV

    - run: make -C kernel build ORG=${REGISTRY}:5000

    # TODO: add artifacts for the built images
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: TODO
    #    path: TODO
